WebApplication4/Controllers/ModuleContainerController.cs
using Settings;
using Settings.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class ModuleContainerController : Controller
    {
        // GET: ModuleContainer
        public ActionResult Default(string MenuTitle)
        {
            string siteName = RouteData.Values["site"] as string;

            if (string.IsNullOrEmpty(siteName))
                return new EmptyResult();


            SiteSetting site = new Settings.Settings().getSiteSetting(siteName);

            if (site == null)
                return new EmptyResult();


            Menu page = new Settings.Settings().getMenu(MenuTitle, site.SiteID);

            if (page == null)
                return new EmptyResult();


            List<PageModule> pageModules =
                new PageModuleManager().GetPageModules(page.MenuID);


            Dictionary<int, ModuleInfo> dicModuleInfo =
                (from item in new Settings.Settings().getModuleInfoList(pageModules.Select(obj => obj.ModuleInfoID).ToArray())
                 select item).ToDictionary(obj => obj.ModuleInfoID, obj => obj);


            List<ModuleContainerViewModel> VMs =
                (from item in pageModules
                 select new ModuleContainerViewModel
                 {
                     PageModuleID = item.PageModuleID,
                     PageID = page.MenuID,
                     ModuleInfoID = dicModuleInfo[item.ModuleInfoID].ModuleInfoID,
                     ActionName = dicModuleInfo[item.ModuleInfoID].ModuleView[0].Action,
                     ControllerName = dicModuleInfo[item.ModuleInfoID].ModuleView[0].Controller
                 }).ToList();



            return View(VMs);
        }
    }
}

WebApplication4/Controllers/NavigationController.cs
using Settings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Utility;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class NavigationController : Controller
    {
        #region "Private"
        private static List<MenuViewModel> menuList = null;

        private void InitMenu()
        {
            //if (NavigationController.menuList != null)
            //    return;


            string siteName = RouteData.Values["site"] as string;

            if (string.IsNullOrEmpty(siteName))
                return;

            SiteSetting site = new Settings.Settings().getSiteSetting(siteName);

            if (site == null)
                return;


            List<Menu> list = new Settings.Settings().getMenus(site.SiteID);
            List<MenuViewModel> models = new List<MenuViewModel>();

            Dictionary<int, MenuViewModel> topMenus = GenerateMenuTree(list);

            menuList = topMenus.Values.ToList();
        }


        private Dictionary<int, MenuViewModel> GenerateMenuTree(List<Menu> list)
        {
            // Key: TopMenuID
            // Value: SubMenus
            Dictionary<int, List<MenuViewModel>> dicSubMenus = new Dictionary<int, List<MenuViewModel>>();

            // Key: MenuID
            // Value: MenuViewModel
            Dictionary<int, MenuViewModel> dicMenus = new Dictionary<int, MenuViewModel>();

            // Key: MenuID
            // Value: MenuViewModel
            Dictionary<int, MenuViewModel> topMenus = new Dictionary<int, MenuViewModel>();


            // 做物件轉換，以及產生樹狀清單
            foreach (Menu menu in list)
            {
                if (dicMenus.ContainsKey(menu.MenuID))
                    continue;


                var model = this.ConvertMenu(menu);
                dicMenus.Add(menu.MenuID, model);



                if (!menu.TopMenuID.HasValue)
                {
                    topMenus.Add(menu.MenuID, model);
                }
                else
                {
                    int topID = menu.TopMenuID.Value;

                    if (!dicSubMenus.ContainsKey(topID))
                        dicSubMenus.Add(topID, new List<MenuViewModel>());

                    dicSubMenus[topID].Add(model);


                    // 尋找屬於自己的母節點
                    if (dicMenus.ContainsKey(topID))
                        dicMenus[topID].SubMenu = dicSubMenus[topID];
                }

                // 尋找屬於自己的子節點
                if (dicSubMenus.ContainsKey(menu.MenuID))
                {
                    model.SubMenu = dicSubMenus[menu.MenuID];
                }
            }

            return topMenus;
        }


        private MenuViewModel ConvertMenu(Menu item)
        {
            return new MenuViewModel()
            {
                MenuID = item.MenuID,
                SiteID = item.SiteID,
                Title = item.Title,
                Action = item.Action,
                Controller = item.Controller,
                Class = "",
                IsAction = item.IsAction,
                Link = item.Link,
                PageFilePath = item.PageFilePath,
                SubMenu = new List<MenuViewModel>()
            };
        }
        #endregion


        // GET: Navigation
        public ActionResult Menu()
        {
            this.InitMenu();

            return PartialView("_NavigationPartial", NavigationController.menuList);
        }


        public ActionResult MenuItem(MenuViewModel menu)
        {
            this.InitMenu();

            return PartialView("_MenuItemPartial", menu);
        }


        public ActionResult Breadcrumbs()
        {
            this.InitMenu();


            string siteName = this.RouteData.Values["site"] as string;

            SiteSetting site = new Settings.Settings().getSiteSetting(siteName);

            if (site == null)
                return new EmptyResult();



            //TODO: 這裡不好，要改
            string title = Request.QueryString["MenuTitle"];

            Menu page = new Settings.Settings().getMenu(title, site.SiteID);
            Menu topPage = page;


            List<MenuViewModel> models = new List<MenuViewModel>() { this.ConvertMenu(page) };

            while (topPage.TopMenuID.HasValue)
            {
                topPage = new Settings.Settings().getMenu(page.TopMenuID.Value);

                if (topPage == null)
                    break;

                models.Insert(0, this.ConvertMenu(topPage));
            }

            return PartialView("_BreadcrumbPartial", models);
        }
    }
}

WebApplication4/Controllers/StaticController.cs
using Settings;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication4.Controllers
{
    public class StaticController : Controller
    {
        // GET: Static
        public ActionResult Page(string MenuTitle)
        {
            if (string.IsNullOrEmpty(MenuTitle))
                return new EmptyResult();



            var mgr = new Settings.Settings();



            string siteName = RouteData.Values["site"] as string;
            SiteSetting site = mgr.getSiteSetting(siteName);



            Menu menuInfo = mgr.getMenu(MenuTitle, site.SiteID);



            if (menuInfo == null)
                return new EmptyResult();


            if (MenuTitle.CompareTo(menuInfo.Title) != 0)
                return new EmptyResult();


            string IOPath = System.Web.HttpContext.Current.Server.MapPath(menuInfo.PageFilePath);


            if (!System.IO.File.Exists(IOPath))
                return Redirect("~/");


            string htmlContent =
                System.IO.File.ReadAllText(IOPath);


            return Content(htmlContent, "text/html");
        }
    }
}

WebApplication4/Views/Shared/_BreadcrumbPartial.cshtml
@using WebApplication4.Models

@model IEnumerable<MenuViewModel>
@{
    var menu1 = this.Model.FirstOrDefault();
}

<p>
    麵包屑
</p>
<p style="padding-left: 2em">
    @for (int i = 0; i < this.Model.Count(); i++)
    {
        if (i > 0)
        {
            @(" > ")
        }

        @Html.Action("MenuItem", "Navigation", this.Model.ElementAt(i))
    }
</p>

WebApplication4/Views/Shared/_Layout.cshtml
@using Utility;
@{
    var dto = UriHelper.getCurrentUri();


    var siteSetting = dto.SiteInfo;
}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@siteSetting.SiteName</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body style="background-color:azure;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@

                <img src="@Url.Content("~/" + siteSetting.Logo)" width="75px" height="75px" alt="logo" />


                @siteSetting.HeaderText

            </div>
            <div class="navbar-collapse collapse">

                @Html.Action("Menu", "Navigation")

            </div>
        </div>
    </div>
 
    <div class="container body-content">
        <br />
        <br />
        <br />
        <br />
        <p style="font-size:large; color: brown; text-align: right;"> This is Skin1 </p>

        @RenderBody()
        <hr />
        <div>
            @Html.Action("Breadcrumbs", "Navigation")
        </div>

        <footer>
            @siteSetting.FooterText
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication4/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    <style>
        body {
            background-color: dimgrey;
            color: white;
        }

        a:hover {
            color: coral;
        }
    </style>
</head>
<body style="background-color: darkgray;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Action("Menu", "Navigation")
            </div>
        </div>
    </div>
    <div class="container body-content">
        <br />
        <br />
        <p style="font-size:large; color: brown; text-align: right;"> This is Skin2 </p>
        @RenderBody()
        <hr />
        <div>
            @Html.Action("Breadcrumbs", "Navigation")
        </div>
        <footer>
            <p> 這裡是頁尾 </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WebApplication4/Views/Shared/_MenuItemPartial.cshtml
@using WebApplication4.Models
@model MenuViewModel

@if (!string.IsNullOrWhiteSpace(Model.PageFilePath))
{
    @Html.ActionLink(Model.Title, "Page", "Static", new { MenuTitle = Model.Title }, null)
}
else if (!string.IsNullOrEmpty(Model.Link))
{
    <a href="@Model.Link" target="_blank">@Model.Title</a>
}
else
{

    @*
        if (this.Model.UrlParams == null)
        {
            this.Model.UrlParams = new Dictionary<string, string>();
        }


        this.Model.UrlParams.Add("MenuTitle", this.Model.Title);


        RouteValueDictionary UrlParam = new RouteValueDictionary(this.Model.UrlParams);

        foreach (var item in this.Model.UrlParams)
        {
            UrlParam.Add(item.Key, item.Value);
        }


        @Html.ActionLink(Model.Title, "Default", "ModuleContainer", UrlParam, null)
    *@


    @Html.ActionLink(Model.Title, "Default", "ModuleContainer", new { MenuTitle = Model.Title }, null)
}

WebApplication4/Views/Shared/_NavigationPartial.cshtml
@using WebApplication4.Models
@model IEnumerable<MenuViewModel>

<!--- Sidemenu -->
<div id="sidebar-menu">
    <ul class="nav navbar-nav">
        @foreach (var menu in Model)
        {
            if (menu.SubMenu != null)
            {
                <li class="has_sub">
                    @Html.Action("MenuItem", "Navigation", menu)

                    <ul class="list-unstyled">
                        @foreach (MenuViewModel subMenu in menu.SubMenu)
                        {
                            <li>
                                @Html.Action("MenuItem", "Navigation", subMenu)
                            </li>
                        }
                    </ul>
                </li>
            }
            else
            {
                <li>
                    @Html.Action("MenuItem", "Navigation", menu)
                </li>
            }
        }
    </ul>
</div>