MVC3/Controllers/AjaxController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC3.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult GoHome()
        {
            string url = Url.Action("Index", "Home");

            return Json(url);
        }


        public ActionResult GetVillage(int id = -1)
        {
            List<Village> list = new List<Village>()
            {
                new Village() { VillageId = 1, VillageName = "First" },
                new Village() { VillageId = 2, VillageName = "Second" },
            };


            if (id > -1)
                list = list.Where(obj => obj.VillageId == id).ToList();


            string result = "";
            if (list.Count <= 0)
            {
                //讀取資料庫錯誤
                result = JsonConvert.SerializeObject(new List<Village>());
                return Json(result);
            }
            else
            {
                result = JsonConvert.SerializeObject(list);
                return Json(result);
            }
        }
    }


    internal class Village
    {
        public int VillageId { get; set; }

        public string VillageName { get; set; }
    }
}

MVC3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Created()
        {
            string Name = Request.Form["Name"];
            string Gender = Request.Form["Gender"];
            string Region = Request.Form["Region"];
            string Desc = Request.Form["Desc"];


            Models.RegisterViewModel model = new Models.RegisterViewModel()
            {
                Name = Name,
                Gender = Gender,
                Region = Region,
                Desc = Desc
            };

            
            return View(model);
        }



        public ActionResult AjaxGo()
        {
            return View();
        }
    }
}

MVC3/Views/Home/AjaxGo.cshtml

@{
    ViewBag.Title = "AjaxGo";
    Layout = "~/Views/Shared/_LayoutPractice.cshtml";
}

@section ScriptArea{
    <script>
        function getVillages(intID) {
            var url = "@Url.Action("GetVillage", "Ajax")";

            var postData = {};
                //(intID == null || intID == undefined) ? {} : { "id": intID };


            if (intID != undefined && intID != null)
                url = url + "?id=" + intID;


            $.ajax({
                type: "POST",
                url: url,
                data: postData,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                async: false,
                success: function (data) {
                    alert(JSON.stringify(data));
                },
                failure: function (errMsg) {
                }
            });
        }



        function goHome() {
            var url = "@Url.Action("GoHome", "Ajax")";

            var postData = {};


            $.ajax({
                type: "POST",
                url: url,
                data: postData,
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                async: false,
                success: function (data) {
                },
                failure: function (errMsg) {
                }
            });
        }






        $(document).ready(function () {

            $("#testbtn").click(function () {
                var val = $("#VillageId").val();
                var intID = parseInt(val);

                getVillages(intID);
            });


            $("#GoHome").click(function () {
                goHome();
            });
        });
    </script>
}

<div>
    <h4>AjaxGo</h4>

    <input type="number" id="VillageId" value="1" />
    <button type="button" id="testbtn">btn123</button>

    <hr />
    <button type="button" id="GoHome">GoHome</button>
</div>

MVC3/Views/Home/Created.cshtml
@model MVC3.Models.RegisterViewModel

@{
    ViewBag.Title = "Created";
    Layout = "~/Views/Shared/_LayoutPractice.cshtml";
}

<h2>Created</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RegisterViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Region, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Region, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Region, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Desc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Desc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Desc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC3/Views/Home/Index.cshtml
@{
    int siteID = Settings.Util.getSiteID();

    var siteSkin = new Settings.Settings().getSiteSkin(siteID);

    this.ViewBag.Title = "Home Page";
    this.Layout = "~" + siteSkin.FilePath;
}



@*<iframe width="150" height="120" src="https://www.youtube.com/embed/GRHy0FgrJrw" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>*@


<div>
    <form method="post" action="@Url.Action("Created", "Home")">
        <table>
            <tr><th> 姓名 </th><td> <input type="text" name="Name" /> </td></tr>
            <tr><th> 性別 </th><td> 男 <input type="radio" name="Gender" value="male" /> / 女 <input type="radio" name="Gender" value="female" /> </td></tr>
            <tr><th> 區域 </th><td> <select name="Region"><option value="KH" selected="selected">高雄</option><option value="TP">台北</option></select> </td></tr>
            <tr><th> 備註 </th><td> <textarea name="Desc"></textarea> </td></tr>
            <tr><td colspan="2"> <button type="submit"> 送出 </button> </td></tr>
        </table>
    </form>
</div>


<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h3>Getting started</h3>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
    </div>
</div>